// @dart=2.19
import 'dart:convert';
import 'dart:io';

/// Configuration: edit these paths for your project
const arbDir = 'lib/core/l10n'; // Folder containing ARB files
const outputPath = 'lib/core/localization/remote_app_localizations.dart';

/// Entry point
void main(List<String> args) {
  final arbFiles = Directory(arbDir)
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.arb'))
      .toList();

  if (arbFiles.isEmpty) {
    stderr.writeln('❌ No ARB files found in $arbDir');
    exit(1);
  }

  final buffer = StringBuffer()
    ..writeln('// GENERATED — DO NOT EDIT')
    ..writeln('// Generated by tool/generate_remote_app_localizations.dart')
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln("import 'package:your_app/core/I10n/generated/app_localizations.dart';")
    ..writeln()
    ..writeln('class RemoteAppLocalizations extends AppLocalizations {')
    ..writeln('  final AppLocalizations _fallback;')
    ..writeln('  final Map<String, String> _ov;')
    ..writeln('  RemoteAppLocalizations(Locale locale, this._fallback, this._ov) : super(locale.languageCode);')
    ..writeln();

  // Process the first ARB file (default language) for keys & placeholders
  final defaultArb = arbFiles.first;
  final content = json.decode(defaultArb.readAsStringSync()) as Map<String, dynamic>;

  final keys = content.keys
      .where((k) => !k.startsWith('@') && content[k] is String)
      .toList()
    ..sort();

  for (final key in keys) {
    final meta = content['@$key'] as Map<String, dynamic>?;
    final placeholders = meta?['placeholders'] as Map<String, dynamic>?;

    if (placeholders != null && placeholders.isNotEmpty) {
      final phs = placeholders.keys.toList();
      final params = phs.map((p) => 'Object $p').join(', ');
      final args = phs.join(', ');

      buffer
        ..writeln('  @override')
        ..writeln('  String $key($params) {')
        ..writeln("    final t = _ov['$key'];")
        ..writeln(
            '    if (t != null) return ${phs.fold<String>('t', (acc, p) => "$acc.replaceAll('{$p}', $p.toString())")};')
        ..writeln('    return _fallback.$key($args);')
        ..writeln('  }')
        ..writeln();
    } else {
      buffer
        ..writeln('  @override')
        ..writeln("  String get $key => _ov['$key'] ?? _fallback.$key;")
        ..writeln();
    }
  }

  buffer.writeln('}');

  // Write output
  final outFile = File(outputPath);
  outFile.createSync(recursive: true);
  outFile.writeAsStringSync(buffer.toString());

  stdout.writeln('✅ RemoteAppLocalizations generated at $outputPath');
}
