// GENERATED — DO NOT EDIT
// Generated by tool/generate_remote_app_localizations.dart
import 'package:flutter/widgets.dart';

import '../l10n/app_localizations.dart';

class RemoteAppLocalizations extends AppLocalizations {
  final AppLocalizations _fallback;
  final Map<String, String> _ov;
  RemoteAppLocalizations(Locale locale, this._fallback, this._ov)
    : super(locale.languageCode);

  @override
  String get currentLocaleLabel =>
      _ov['currentLocaleLabel'] ?? _fallback.currentLocaleLabel;

  @override
  String get changeLanguage => _ov['changeLanguage'] ?? _fallback.changeLanguage;

  @override
  String get hello => _ov['hello'] ?? _fallback.hello;

  @override
  String get localizationTestDescription =>
      _ov['localizationTestDescription'] ?? _fallback.localizationTestDescription;

  @override
  String get localizationTestTitle =>
      _ov['localizationTestTitle'] ?? _fallback.localizationTestTitle;

  @override
  String get toggleToArabic => _ov['toggleToArabic'] ?? _fallback.toggleToArabic;

  @override
  String get toggleToEnglish =>
      _ov['toggleToEnglish'] ?? _fallback.toggleToEnglish;

  @override
  String get welcome => _ov['welcome'] ?? _fallback.welcome;

}
